#ifndef DLT_H
#define DLT_H

#include <utility>
#include <Eigen/Dense>

using namespace std;
using namespace Eigen;

namespace math
{
	using Correspondence = pair< VectorXd, VectorXd >;
	
	/** Implements the algorithm Direct Linear Transformation, to solve overdetermined linear systems in the form Ax = 0,
	 * generated by correlations of points. This implementation normalizes the system before computing the results and
	 * denormalizes it afterwards.
	 */
	class Dlt
	{
	public:
		/** Computes the results of the generated system. */
		static VectorXd compute( vector< Correspondence > correlations );
	private:
		Dlt();
	};
}

#endif